# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            The Official Fealty Site
tagline:          
description:      "Fealty is <i>complicated</i>"
url:              https://fealtygame.com
baseurl:          
                  # the optional subpath of your site, e.g. "/my-jekyll-site/"
                  # This will apply to all pages in your Jekyll site.

author:
  name:           FealtyDev
  url:            https://twitter.com/FealtyDev

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/my-jekyll-site/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            0.0.1

gameVersion:        0.10.1

# github:
#  repo:             https://github.com/karloespiritu/blackdoc
